name: release.yml
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v7
        with:
          name: img2ascii-binaries
          path: dist

      - name: Upload release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload "${{ inputs.tag }}" dist/* --clobber
